### ISSUE TITLE
Are fully dynamic views based on dynamic models possible?

### ISSUE THREAD

**Issue by kristianmandrup** [SpoonX/aurelia-view-manager#15]
I'm trying to figure out if Aurelia supports fully dynamic views and view models?

I'd like to have a blank slate (canvas), where the user can drag and drop elements to update an underlying model (schema) and where the canvas then responds by rendering the corresponding views (elements/components) to reflect this model.

Does view-manager (or Aurelia) currently support this or what would be need for this to be possible? Thanks!

**Comment by bas080** [comment]
This is possible. Would like to start working on it after some of my other projects are more stable. If you can share some examples with me of what it is your looking for I might take it into account when developing.

**Comment by kristianmandrup** [comment]
Something like in this article:

https://www.sitepoint.com/composition-aurelia-report-builder/

``` html
<compose view-model="hello-world"
         model.bind="{ demo: 'test' }"
         view.bind="pathToHelloWorld"></compose>
```

``` html
    <li repeat.for="widget of widgets" 
        class="au-animate" 
        title="${widget.type}">
          <i class="fa ${widget.icon}"/> ${widget.name}
    </li>
```

and what I could find here:

https://gist.github.com/kristianmandrup/b79aca9f7e314082404a02bfa0513465

I've started building a UI/UX app prototype editor, and I'd like the user to able to preview the screens (ie. components) in different UI frameworks.

**Comment by jawa-the-hutt** [comment]
I'm interested in this kind of feature as well.  I'd also be interested in helping with the overall design/feature strategy.

I mentioned something similar in the Gitter channel yesterday and then noticed an issue opened on the aurelia-forms project:  SpoonX/aurelia-form#46

Another item to reference is something I found in the comments on the Report Builder link above:  https://www.youtube.com/watch?v=1V8aIIdgV_8

It's built in Aurelia as well.  It wouldn't necessarily align with the SpoonX stuff, but it could serve as something to generate ideas on where to take this.

**Comment by kristianmandrup** [comment]
@jawa-the-hutt Oh yeah! I remember stumbling across that project of yours last year I think.
Let's do it!!!

**Comment by RWOverdijk** [comment]
What's the status here?

**Comment by bas080** [comment]
@RWOverdijk, the "dymanic" rendering is possible. The UI builder has not been built. This can be closed as it is a to broad of a topic to discuss in aurelia-view-manager. Maybe create a project named `aurelia-dashboard` where discussion and development can continue.

**Comment by RWOverdijk** [comment]
@bas080 I propose then moving this to swan example. Could you create the ticket and reference it from here?
