### ISSUE TITLE
Missing types in d.ts file

### ISSUE THREAD

**Issue by tiborfsk** [SpoonX/aurelia-view-manager#29]
I cannot build my project using _aurelia-view-manager_ and _typescript_ with errors in **dist/aurelia-view-manager.d.ts**:

```
Cannot find name 'ViewEngine'
Cannot find name 'ViewCompileInstructions'
Cannot find name 'ResourceLoadContext'
Cannot find name 'ViewFactory'
```

The problem is fixed when I add these missing types to import statement on **line 3**: 
```
import {viewStrategy,useViewStrategy,ViewEngine,ViewCompileInstruction,ResourceLoadContext,ViewFactory} from 'aurelia-templating';
```

**Comment by VMBindraban** [comment]
@bas080

**Comment by RWOverdijk** [comment]
@Tibest That file is just for typings, right? How does that stop the build? I haven't tried that before so maybe you can help :)

**Comment by tiborfsk** [comment]
Yes it is for typings. Actually gulp build does not stop. Sorry for inaccurate info. But when building docker image with my project it detects those error messages and stops. It would help me if I have not to manage docker to ignore gulp errors (or making another workarounds)

**Comment by RWOverdijk** [comment]
I understand. I'm not sure if I can automate this process in the d.ts file, but I guess it's worth trying.

**Comment by Kukks** [comment]
https://github.com/SpoonX/aurelia-view-manager/pull/35
Would this be sufficient?

**Comment by RWOverdijk** [comment]
Hm well, maybe. I honestly don't know how this works. I've never had to have typings from external projects before, I just told it to ignore them, or point to their d.ts files (usually part of their own package.json). I think you can try it locally using linking, and see if it works?

**Comment by Kukks** [comment]
I edited my installed package to reflect the updated d.ts file and it stopped complaining. :)
Default Webpack typescript skeleton production builds get halted when typescript compilation errors are found.

**Comment by RWOverdijk** [comment]
Meh.. Alright then! I'll merge and release it later today :)

**Comment by RWOverdijk** [comment]
Published! :)
