### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by RWOverdijk** [SpoonX/aurelia-view-manager#7]
> Views are created by a ViewFactory, so they don’t go through DI directly, but their internal components are created by DI. If you create a custom ViewStrategy, you can control whether or not the view is relative to the view model or not. The strategies implement a method “makeRelativeTo”. You can implement that but just ignore the file path it provides.

We could say that defaults from plugins are relative to the plugin. Anything user-provided is relative to the project.

**Comment by bas080** [comment]
Relative to plugin works when `./` is not prepended. Document this in a new chapter named `Paths`.

**Comment by doktordirk** [comment]
'./' and '../' -> relative to current module(id)
'moduleId/' -> relative to module(id)
'else/' -> relative to app.js

**Comment by bas080** [comment]
@RWOverdijk, this is solved.

**Comment by RWOverdijk** [comment]
Aye!
